// Layer registry: drives both the map layers and the legend rows.
// Order matches plan.md. Fill layers get 33% fill-opacity / 66% border
// opacity by default; the fault layer is line-only at 70% opacity.
export const LAYERS = [
  {
    id: "fire-veryhigh",
    label: "Very high wildfire risk",
    dataUrl: "/data/fire_hazard_veryhigh.json",
    colorVar: "--fire-veryhigh",
    kind: "fill",
    pattern: { type: "stripes", width: 3, gap: 0.5, angle: -65 },
    defaultVisible: true,
  },
  {
    id: "fire-high",
    label: "High wildfire risk",
    dataUrl: "/data/fire_hazard_high.json",
    colorVar: "--fire-high",
    kind: "fill",
    pattern: { type: "stripes", width: 2, angle: -65 },
    defaultVisible: true,
  },
  {
    id: "flood-100",
    label: "100 year flood risk",
    dataUrl: "/data/flood_100yr.json",
    colorVar: "--flood-100",
    kind: "fill",
    pattern: { type: "stripes", width: 4, gap: 0.5, angle: 0 },
    defaultVisible: true,
  },
  {
    id: "flood-500",
    label: "500 year flood risk",
    dataUrl: "/data/flood_500yr.json",
    colorVar: "--flood-500",
    kind: "fill",
    pattern: { type: "stripes", width: 2, gap: 2, angle: 0 },
    defaultVisible: true,
  },
  {
    id: "faults",
    label: "Major earthquake faults",
    dataUrl: "/data/faults.json",
    colorVar: "--fault",
    kind: "line",
    width: 1,
    lineOpacity: 0.8,
    defaultVisible: true,
  },
  {
    id: "liquefaction",
    label: "Liquefaction zone",
    dataUrl: "/data/liquefaction.json",
    colorVar: "--liquefaction",
    kind: "fill",
    pattern: { type: "dots" },
    defaultVisible: true,
  },
  {
    id: "landslide",
    label: "Landslide zone",
    dataUrl: "/data/landslide.json",
    colorVar: "--landslide",
    kind: "fill",
    pattern: { type: "dots" },
    noBorder: true,
    defaultVisible: false,
  },
  {
    id: "tsunami",
    label: "Tsunami hazard area",
    dataUrl: "/data/tsunami.json",
    colorVar: "--tsunami",
    kind: "fill",
    defaultVisible: true,
  },
  {
    id: "dam-failure",
    label: "Dam failure inundation area",
    dataUrl: "/data/dam_inundation.json",
    colorVar: "--dam-failure",
    kind: "fill",
    defaultVisible: true,
  },
];
